language: node_js
# 穩定更新版
node_js:
  - lts/*
install: 
- npm install

script:
- npm test # test
- npm build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master